config/routes.rb
Rails.application.routes.draw do
  resources :assignments do
  	resources :problems
  end
  root 'assignments#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/assignment.rb
class Assignment < ActiveRecord::Base
	has_many :problems, dependent: :destroy
end

app/models/problem.rb
class Problem < ActiveRecord::Base
  belongs_to :assignment
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/assignments_controller.rb
class AssignmentsController < ApplicationController
	before_action :find_assignment, only: [:show, :edit, :update, :destroy]
	def index
		@assignments = Assignment.all.order("created_at DESC")
	end

	def show
	end

	def new
		@assignment = Assignment.new
	end

	def create
		@assignment = Assignment.new(assignment_params)
		if @assignment.save
			redirect_to @assignment
		else
			render 'new'
		end
	end

	def edit
	end

	def update
		if @assignment.update(assignment_params)
			redirect_to @assignment
		else
			render 'edit'
		end
	end

	def destroy
		@assignment.destroy
		redirect_to root_path
	end

	private

	def assignment_params
		params.require(:assignment).permit(:date, :assignment, :difficulty)
	end

	def find_assignment
		@assignment = Assignment.find(params[:id])
	end
end

app/controllers/problems_controller.rb
class ProblemsController < ApplicationController
	def create
		@assignment = Assignment.find(params[:assignment_id])
		@problem = @assignment.problems.create(params[:problem].permit(:name, :description))

		redirect_to assignment_path(@assignment)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/assignments/_form.html.erb
<%= simple_form_for(@assignment, html: { class: 'form-horizontal' }) do |f| %>
  <%= f.input :date, label: "Date" %>
  <%= f.input :assignment, label: "What assignment did you receive", input_html: { class: "form-control" } %>
  <%= f.input :difficulty, label: "How difficult was the assignment?", input_html: { class: "form-control" } %>
  <br/>
  <%= f.button :submit %>
<% end %>

app/views/assignments/edit.html.erb
<h1>Edit Workout</h1>
<%= render 'form' %>
<%= link_to "Cancel", root_path %>

app/views/assignments/index.html.erb
<div id="index_assignments">
  <% @assignments.each do |assignment| %>
    <h2>
      <%= link_to assignment.date.strftime("%A %B %d"), assignment %>
    </h2>
    <h3>
      <span>Assignment:</span>
      <%= assignment.assignment %>
    </h3>
  <% end %>
</div>

app/views/assignments/new.html.erb
<h1>New Assignment</h1>
<%= render 'form' %>
<%= link_to "Cancel", root_path %>

app/views/assignments/show.html.erb
<div id="assignment">
  <h3>
    <%= @assignment.date.strftime("%B %d") %>: <%= @assignment.assignment %> (Difficulty: <%= @assignment.difficulty %>)
  </h3>
</div>
<div id="problems">
  <h2>Problems</h2>
  <%= render @assignment.problems %>
  <h3>Add a Problem</h3>
  <%= render "problems/form" %>
</div>
<%= link_to "Back", root_path %>
|
<%= link_to "Edit", edit_assignment_path(@assignment) %>
|
<%= link_to "Delete", assignment_path(@assignment), method: :delete, data: { confirm: "Are you sure?" } %>

app/views/layouts/application.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html></html>
<head>
  <title>Homework Journal Application</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <nav class="navbar navbar-default">
    <div class="container">
      <div class="navbar-header">
        <%= link_to "Homework Journal", root_path, class: "navbar-brand" %>
      </div>
      <div class="nav navbar-nav navbar-right">
        <%= link_to "New Assignment", new_assignment_path, class: "nav navbar-link" %>
      </div>
    </div>
  </nav>
  <div class="container">
    <%= yield %>
  </div>
</body>

app/views/problems/_form.html.erb
<%= simple_form_for([@assignment, @assignment.problems.build]) do |f| %>
  <%= f.input :name, input_html: { class: "form-control" } %>
  <%= f.input :description, input_html: { class: "form-control" } %>
  <br/>
  <%= f.button :submit %>
<% end %>

app/views/problems/_problem.html.erb
<p>
  <%= problem.name %>: <%= problem.description %>
</p>